"""add payment_day and first_month_price to groups

Revision ID: 04389e532fac
Revises: 38a1023c772c
Create Date: 2026-06-28 23:56:37.605191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '04389e532fac'
down_revision: Union[str, None] = '38a1023c772c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('first_month_price', sa.Integer(), nullable=True))
    op.add_column('groups', sa.Column('payment_day', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'payment_day')
    op.drop_column('groups', 'first_month_price')
    # ### end Alembic commands ###
