"""add_teacher_salary_fields_to_groups

Revision ID: 0b2d86c2c3b9
Revises: 25d2c6a8ff31
Create Date: 2026-06-29 01:18:55.358120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0b2d86c2c3b9'
down_revision: Union[str, None] = '25d2c6a8ff31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('teacher_salary_type', sa.String(length=10), nullable=True))
    op.add_column('groups', sa.Column('teacher_salary_value', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'teacher_salary_value')
    op.drop_column('groups', 'teacher_salary_type')
    # ### end Alembic commands ###
