"""add ai_settings table

Revision ID: 117206b64311
Revises: fc2aed3f414a
Create Date: 2026-06-29 04:45:36.526809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '117206b64311'
down_revision: Union[str, None] = 'fc2aed3f414a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('openai_api_key', sa.Text(), nullable=True),
    sa.Column('openai_model', sa.String(length=100), nullable=False),
    sa.Column('gemini_api_key', sa.Text(), nullable=True),
    sa.Column('gemini_model', sa.String(length=100), nullable=False),
    sa.Column('claude_api_key', sa.Text(), nullable=True),
    sa.Column('claude_model', sa.String(length=100), nullable=False),
    sa.Column('deepseek_api_key', sa.Text(), nullable=True),
    sa.Column('deepseek_model', sa.String(length=100), nullable=False),
    sa.Column('token_budget', sa.Integer(), nullable=False),
    sa.Column('enabled_modules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_settings')
    # ### end Alembic commands ###
