"""add payments and coins tables

Revision ID: 143281bf562f
Revises: 708b36276c1d
Create Date: 2026-06-28 20:30:31.501195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '143281bf562f'
down_revision: Union[str, None] = '708b36276c1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coin_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('coins', sa.Integer(), nullable=False),
    sa.Column('txn_type', sa.Enum('earned', 'spent', 'bonus', 'penalty', name='cointxntype'), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('payment_type', sa.Enum('monthly', 'registration', 'material', 'other', name='paymenttype'), nullable=False),
    sa.Column('method', sa.Enum('cash', 'card', 'transfer', name='paymentmethod'), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('received_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['received_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('coin_transactions')
    # ### end Alembic commands ###
