"""payment_audit_and_refund

Revision ID: 173914fa0019
Revises: 24bf46befc1d
Create Date: 2026-06-29 02:41:00.671853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '173914fa0019'
down_revision: Union[str, None] = '24bf46befc1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_refunds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('refunded_by_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['refunded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('payments', sa.Column('created_by_id', sa.UUID(), nullable=True))
    op.add_column('payments', sa.Column('updated_by_id', sa.UUID(), nullable=True))
    op.add_column('payments', sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.text('now()')))
    op.add_column('payments', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'payments', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'payments', 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_column('payments', 'updated_at')
    op.drop_column('payments', 'created_at')
    op.drop_column('payments', 'updated_by_id')
    op.drop_column('payments', 'created_by_id')
    op.drop_table('payment_refunds')
    # ### end Alembic commands ###
