"""add_discounts_table

Revision ID: 1d512e242e75
Revises: e84abd8281c6
Create Date: 2026-06-28 23:36:39.232894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1d512e242e75'
down_revision: Union[str, None] = 'e84abd8281c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
