"""add_payment_start_date_to_groups

Revision ID: 25d2c6a8ff31
Revises: cf7d5e518b1b
Create Date: 2026-06-29 01:13:03.996629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '25d2c6a8ff31'
down_revision: Union[str, None] = 'cf7d5e518b1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('payment_start_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'payment_start_date')
    # ### end Alembic commands ###
