"""payment_discount_snapshot

Revision ID: 3605640db819
Revises: 8da4682c7503
Create Date: 2026-06-29 03:22:55.866166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3605640db819'
down_revision: Union[str, None] = '8da4682c7503'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('discount_snapshot', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'discount_snapshot')
    # ### end Alembic commands ###
