"""add_notification_payment_settings

Revision ID: 372ed6e4c336
Revises: a8e2f51037cc
Create Date: 2026-06-30 16:10:45.547352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '372ed6e4c336'
down_revision: Union[str, None] = 'a8e2f51037cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('general_settings', sa.Column('notif_email', sa.Boolean(), nullable=True))
    op.add_column('general_settings', sa.Column('notif_sms', sa.Boolean(), nullable=True))
    op.add_column('general_settings', sa.Column('notif_telegram', sa.Boolean(), nullable=True))
    op.add_column('general_settings', sa.Column('notif_payment', sa.Boolean(), nullable=True))
    op.add_column('general_settings', sa.Column('notif_attendance', sa.Boolean(), nullable=True))
    op.add_column('general_settings', sa.Column('notif_exams', sa.Boolean(), nullable=True))
    op.add_column('general_settings', sa.Column('payment_methods', sa.String(length=200), nullable=True))
    op.add_column('general_settings', sa.Column('late_fee_percent', sa.String(length=10), nullable=True))
    op.add_column('general_settings', sa.Column('payment_day', sa.String(length=5), nullable=True))
    op.alter_column('integration_settings', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('telegram_sources', 'last_message_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('telegram_sources', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('telegram_sources', 'vacancies_found',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('telegram_sources', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('telegram_sources', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('telegram_sources', 'vacancies_found',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('telegram_sources', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('telegram_sources', 'last_message_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('integration_settings', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('general_settings', 'payment_day')
    op.drop_column('general_settings', 'late_fee_percent')
    op.drop_column('general_settings', 'payment_methods')
    op.drop_column('general_settings', 'notif_exams')
    op.drop_column('general_settings', 'notif_attendance')
    op.drop_column('general_settings', 'notif_payment')
    op.drop_column('general_settings', 'notif_telegram')
    op.drop_column('general_settings', 'notif_sms')
    op.drop_column('general_settings', 'notif_email')
    # ### end Alembic commands ###
