"""add_created_at_to_users

Revision ID: 38a1023c772c
Revises: 1d512e242e75
Create Date: 2026-06-28 23:41:18.019668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '38a1023c772c'
down_revision: Union[str, None] = '1d512e242e75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###
