"""create_discounts_table

Revision ID: 41570bdf793b
Revises: d0577c2efdff
Create Date: 2026-06-29 01:45:45.950055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '41570bdf793b'
down_revision: Union[str, None] = 'd0577c2efdff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('discount_type', sa.Enum('percent', 'fixed', name='discounttype'), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('active', 'expired', 'paused', name='discountstatus'), nullable=False),
    sa.Column('approved_by', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discounts')
    # ### end Alembic commands ###
