"""add student_status to users

Revision ID: 44e862dc6c68
Revises: 4edd649accbb
Create Date: 2026-06-28 20:13:36.599544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '44e862dc6c68'
down_revision: Union[str, None] = '4edd649accbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('student_status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'student_status')
    # ### end Alembic commands ###
