"""add group_type and price to groups

Revision ID: 4edd649accbb
Revises: cae8fcede95e
Create Date: 2026-06-28 20:01:25.725871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4edd649accbb'
down_revision: Union[str, None] = 'cae8fcede95e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('group_type', sa.String(length=20), nullable=True))
    op.add_column('groups', sa.Column('price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'price')
    op.drop_column('groups', 'group_type')
    # ### end Alembic commands ###
