"""add_branch_id_to_rooms

Revision ID: 6e8115a9f5db
Revises: cdc2f37c07cd
Create Date: 2026-06-29 04:09:34.272186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6e8115a9f5db'
down_revision: Union[str, None] = 'cdc2f37c07cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('branch_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'rooms', 'branches', ['branch_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.drop_column('rooms', 'branch_id')
    # ### end Alembic commands ###
