"""extend leads with crm fields

Revision ID: 708b36276c1d
Revises: e860e3141e30
Create Date: 2026-06-28 20:21:27.055146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '708b36276c1d'
down_revision: Union[str, None] = 'e860e3141e30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('course_name', sa.String(length=120), nullable=True))
    op.add_column('leads', sa.Column('stage', sa.String(length=30), nullable=False, server_default='yangi'))
    op.add_column('leads', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('leads', sa.Column('created_date', sa.Date(), nullable=True))
    op.add_column('leads', sa.Column('salesperson_id', sa.UUID(), nullable=True))
    op.alter_column('leads', 'phone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.create_foreign_key(None, 'leads', 'users', ['salesperson_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.alter_column('leads', 'phone',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('leads', 'salesperson_id')
    op.drop_column('leads', 'created_date')
    op.drop_column('leads', 'notes')
    op.drop_column('leads', 'stage')
    op.drop_column('leads', 'course_name')
    # ### end Alembic commands ###
