"""add_is_open_to_group_lesson_done

Revision ID: 811b8ec05ba8
Revises: af19126327c1
Create Date: 2026-06-29 02:13:01.087787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '811b8ec05ba8'
down_revision: Union[str, None] = 'af19126327c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_lesson_done', sa.Column('is_open', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_lesson_done', 'is_open')
    # ### end Alembic commands ###
