"""add fcm_token to users

Revision ID: 8173baee6034
Revises: fc3dcce03eb1
Create Date: 2026-07-01 20:49:58.268817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8173baee6034'
down_revision: Union[str, None] = 'fc3dcce03eb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fcm_token', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'fcm_token')
    # ### end Alembic commands ###
