"""add practicum tables

Revision ID: 94629893604d
Revises: 6e8115a9f5db
Create Date: 2026-06-29 04:26:46.961023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '94629893604d'
down_revision: Union[str, None] = '6e8115a9f5db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practicum_teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('mentor', sa.String(length=200), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('stack', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('links', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('members', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('practicum_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('column', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('github', sa.String(length=500), nullable=True),
    sa.Column('figma', sa.String(length=500), nullable=True),
    sa.Column('assignees', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('checklist', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('comments', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('activity', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['practicum_teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('practicum_tasks')
    op.drop_table('practicum_teams')
    # ### end Alembic commands ###
