"""add exam_type to lessons

Revision ID: cae8fcede95e
Revises: 0dbce5e8a84b
Create Date: 2026-06-28 19:54:23.897489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cae8fcede95e'
down_revision: Union[str, None] = '0dbce5e8a84b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('exam_type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'exam_type')
    # ### end Alembic commands ###
