"""add_branch_model

Revision ID: cdc2f37c07cd
Revises: 3605640db819
Create Date: 2026-06-29 03:44:44.643832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cdc2f37c07cd'
down_revision: Union[str, None] = '3605640db819'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('groups', sa.Column('branch_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'groups', 'branches', ['branch_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_column('groups', 'branch_id')
    op.drop_table('branches')
    # ### end Alembic commands ###
