"""add telegram fields and description to groups

Revision ID: ce3a331710bb
Revises: 04389e532fac
Create Date: 2026-06-28 23:58:40.640732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ce3a331710bb'
down_revision: Union[str, None] = '04389e532fac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('groups', sa.Column('group_link', sa.String(length=200), nullable=True))
    op.add_column('groups', sa.Column('chat_id', sa.String(length=50), nullable=True))
    op.add_column('groups', sa.Column('attendance_topic_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'attendance_topic_id')
    op.drop_column('groups', 'chat_id')
    op.drop_column('groups', 'group_link')
    op.drop_column('groups', 'description')
    # ### end Alembic commands ###
