"""add reason to attendance

Revision ID: cf7d5e518b1b
Revises: ce3a331710bb
Create Date: 2026-06-29 00:58:08.141867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cf7d5e518b1b'
down_revision: Union[str, None] = 'ce3a331710bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance', 'reason')
    # ### end Alembic commands ###
