"""create_discounts_table

Revision ID: d0577c2efdff
Revises: 0b2d86c2c3b9
Create Date: 2026-06-29 01:44:41.964999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd0577c2efdff'
down_revision: Union[str, None] = '0b2d86c2c3b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
