"""add_student_extra_fields

Revision ID: e84abd8281c6
Revises: 14e09ecb76b3
Create Date: 2026-06-28 23:31:16.333380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e84abd8281c6'
down_revision: Union[str, None] = '14e09ecb76b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('passport', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('birth_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('gender', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('region', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('district', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('address', sa.String(length=300), nullable=True))
    op.add_column('users', sa.Column('mother_name', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('mother_phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('father_name', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('father_phone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'father_phone')
    op.drop_column('users', 'father_name')
    op.drop_column('users', 'mother_phone')
    op.drop_column('users', 'mother_name')
    op.drop_column('users', 'address')
    op.drop_column('users', 'district')
    op.drop_column('users', 'region')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'birth_date')
    op.drop_column('users', 'passport')
    # ### end Alembic commands ###
