"""add leads table

Revision ID: e860e3141e30
Revises: 44e862dc6c68
Create Date: 2026-06-28 20:19:30.041612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e860e3141e30'
down_revision: Union[str, None] = '44e862dc6c68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
