"""add_token_version_to_users

Revision ID: fc3dcce03eb1
Revises: 6d09ffe0083f
Create Date: 2026-07-01 17:34:18.052934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fc3dcce03eb1'
down_revision: Union[str, None] = '6d09ffe0083f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_branch_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role', 'branch_id', name='uq_role_branch')
    )
    op.add_column('users', sa.Column('token_version', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token_version')
    op.drop_table('role_branch_permissions')
    # ### end Alembic commands ###
